# Docker and Docker Compose based environment for Symfony.
# See https://github.com/docksal/docksal for more information and documentation.

# This is a shared configuration file that is intended to be stored in the project repo.
# For local overrides:
# - create .docksal/docksal-local.yml file and put local docker-compose configuration overrides there
# - add .docksal/docksal-local.yml to .gitignore

# Docksal stiches several docker-compose configuration files together.
# Run "fin config" to see which files are involved and the resulting configuration.

version: "2.1"

services:

# Note: Using default Docksal stack. Only put overrides and extra services here.
  # PHPMyAdmin
  pma:
    hostname: pma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    labels:
      - io.docksal.virtual-host=pma-${VIRTUAL_HOST}

  cli:
    environment:
      - ENVIRONMENT=development

  web:
    environment:
      - ENVIRONMENT=development
